function crearReporte(dataReceptor, dataEmisor, dataOrdenes, dataFactura){

	return new Promise((resolve, reject)=> {

	if(dataFactura === "" || dataReceptor === ""  || dataEmisor === ""){
		reject(undefined)
	}else{
	var ordenes=listaOrdenes(dataOrdenes);
	var content='<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">'
+'<!-- saved from url=(0077)file:///home/nvm/Descargas/factura/factura/ATV_eFAC_00100001010000000008.html -->'
+'<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">'
	
	+'<title></title>'
	+'<meta name="GENERATOR" content="LibreOffice 4.1.6.2 (Linux)">'
	+'<meta name="CREATED" content="20190421;225338000000000">'
	+'<meta name="CHANGED" content="20190421;225338000000000">'
	+'<meta name="AppVersion" content="12.0000">'
	+'<meta name="DocSecurity" content="0">'
	+'<meta name="HyperlinksChanged" content="false">'
	+'<meta name="LinksUpToDate" content="false">'
	+'<meta name="ScaleCrop" content="false">'
	+'<meta name="ShareDoc" content="false">'
	+'<style type="text/css">'
	+'<!--'
		+'@page { size: 8.5in 11in; margin-left: 0.21in; margin-right: 0.32in; margin-top: 0.19in }'
		+'P { margin-bottom: 0in; direction: ltr; widows: 2; orphans: 2 }'
		+'P.western { font-family: "Arial", serif; font-size: 8pt; so-language: es-ES; font-weight: bold }'
		+'P.cjk { font-family: "Arial"; font-size: 8pt; so-language: es-ES; font-weight: bold }'
		+'P.ctl { font-family: "Arial"; font-size: 8pt; so-language: es-ES; font-weight: bold }'
		+'H1 { margin-left: 0.1in; margin-top: 0.04in; margin-bottom: 0in; direction: ltr; widows: 2; orphans: 2; page-break-after: auto }'
		+'H1.western { font-family: "Courier New", serif; font-size: 11pt; so-language: es-ES }'
		+'H1.cjk { font-family: "Courier New"; font-size: 11pt; so-language: es-ES }'
		+'H1.ctl { font-family: "Courier New"; font-size: 11pt; so-language: es-ES }'
		+'A:link { so-language: zxx }'
	+'-->'
	+'</style>'
+'</head>'
+'<body lang="en-US" dir="LTR">'
+'<p lang="es-ES" class="western" style="margin-top: 0.01in; font-weight: normal">'
+'<br>'
+'</p>'
+'<h1 lang="es-ES" class="western" style="margin-top: 0.07in">'
+'IMAGINE CORP.<span class="sd-abs-pos" style="position: absolute; top: -0.09in; left: 5.83in; width: 160px"><img src="logo.jpg" width="200" height="100" border="0"></span></h1>'
+'<p lang="es-ES" class="western" align="LEFT" style="margin-left: 0.1in; margin-top: 0.04in; font-weight: normal">'
+'<font size="2" style="font-size: 11pt"><font face="Courier New, serif"><font size="2" style="font-size: 11pt"><b>DETALLE DE COMPROBANTE</b></font></font></font></p>'
+'<p lang="es-ES" class="western" align="LEFT" style="margin-left: 2.97in; margin-right: 2.41in; text-indent: -0.67in; margin-top: 0.03in; font-weight: normal; line-height: 123%">'
+'<font size="2" style="font-size: 11pt"><font face="Courier New, serif"><font size="2"></font></font></font></p>'
+'<p lang="es-ES" class="western"><br>'
+'</p>'
+'<p lang="es-ES" class="western" style="margin-top: 0in"><br>'
+'</p>'
+'<table width="740" cellpadding="0" cellspacing="0">'
	+'<colgroup><col width="117">'
	+'<col width="329">'
	+'<col width="144">'
	+'<col width="151">'
	+'</colgroup><tbody>'
		+'<tr valign="TOP">'
			+'<td width="117" height="14" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; font-weight: normal"><font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Consecutivo:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; font-weight: normal"><font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.consecutivo+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; font-weight: normal"><font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Plazo'
				+'de crédito:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Clave:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.clave+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Condición'
				+'de Venta:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.condicion_venta+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="27" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Fecha:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">0'+dataFactura.fecha+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Medio de Pago:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-right: 0.14in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.medio_pago+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="20" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Tipo Documento:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.tipo_documento+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
	+'</tbody>'
	+'<tbody>'
		+'<tr valign="TOP">'
			+'<td width="117" height="14" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt"><b>INFORMACIÓN DEL EMISOR O EMPRESA</b></font></font></p>'
			+'</td>'
			+'<td width="329" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="144" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
	+'</tbody>'
	+'<tbody>'
		+'<tr valign="TOP">'
			+'<td width="117" height="17" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Nombre:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.nombre+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Cédula:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.emisor_numero+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Nombre comercial:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.nombrecomercial+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">E-Mail:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><a href="mailto:'+dataEmisor.correo+'"><font size="1" style="font-size: 8pt">'+dataEmisor.correo+'</font></a></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Teléfono:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.telefono+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Fax:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.fax+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Provincia:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.provincia+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Cantón:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.canton+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Distrito:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.distrito+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Barrio:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="36" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Otras Señas:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataEmisor.otras_senas+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border-top: none; border-bottom: 1px solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
	+'</tbody>'
	+'<tbody>'
		+'<tr valign="TOP">'
			+'<td width="117" height="14" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt"><b>INFORMACIÓN DEL CLIENTE</b></font></font></p>'
			+'</td>'
			+'<td width="329" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="144" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border-top: 1px solid #86cdf9; border-bottom: 1.00pt solid #86cdf9; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
	+'</tbody>'
	+'<tbody>'
		+'<tr valign="TOP">'
			+'<td width="117" height="17" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Nombre:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.nombre+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Cédula:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border-top: 1.00pt solid #86cdf9; border-bottom: none; border-left: none; border-right: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.03in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.receptor_numero+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Nombre comercial:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.nombrecomercial+'</font></font></p>'
			+'</td>'
		+'</tr>'
			+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">E-Mail:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><a href="mailto:'+dataReceptor.correo+'"><font size="1" style="font-size: 8pt">'+dataReceptor.correo+'</font></a></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Teléfono:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.telefono+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Fax:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.fax+'</font></font></p>'
			+'</td>'
		 +'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Provincia:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.provincia+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Cantón:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.2in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.canton+'</font></font></p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="16" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Distrito:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.distrito+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.29in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Barrio:</font></font></p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
		+'<tr valign="TOP">'
			+'<td width="117" height="14" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">Otras Señas:</font></font></p>'
			+'</td>'
			+'<td width="329" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="margin-left: 0.04in; margin-top: 0.02in; font-weight: normal">'
				+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataReceptor.otras_senas+'</font></font></p>'
			+'</td>'
			+'<td width="144" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
			+'<td width="151" style="border: none; padding: 0in">'
				+'<p lang="es-ES" style="font-weight: normal"><br>'
				+'</p>'
			+'</td>'
		+'</tr>'
	+'</tbody>'
+'</table>'
+'<p lang="es-ES" class="western"><br>'
+'</p>'
+'<p lang="es-ES" class="western" style="margin-top: 0in"><br>'
+'</p>'
+'<table width="740" cellpadding="1" cellspacing="0">'
	+'<colgroup><col width="35">'
	+'<col width="62">'
	+'<col width="189">'
	+'<col width="36">'
	+'<col width="49">'
	+'<col width="87">'
	+'<col width="87">'
	+'<col width="87">'
	+'<col width="87">'
	+'</colgroup><tbody><tr valign="TOP">'
		+'<td width="35" height="12" bgcolor="#86cdf9" style="border: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Línea</b></font></font></font></p>'
		+'</td>'
		+'<td width="62" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Código</b></font></font></font></p>'
		+'</td>'
		+'<td width="189" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Detalle del Producto</b></font></font></font></p>'
		+'</td>'
		+'<td width="36" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="CENTER" style="margin-left: 0.01in; margin-right: 0.07in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Cant.</b></font></font></font></p>'
		+'</td>'
		+'<td width="49" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Unidad</b></font></font></font></p>'
		+'</td>'
		+'<td width="87" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Precio Unitario</b></font></font></font></p>'
		+'</td>'
		+'<td width="87" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Monto</b></font></font></font></p>'
		+'</td>'
		+'<td width="87" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Descuento</b></font></font></font></p>'
		+'</td>'
		+'<td width="87" bgcolor="#86cdf9" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#ffffff"><font size="1" style="font-size: 8pt"><b>Total</b></font></font></font></p>'
		+'</td>'
	+'</tr>'
 // AQUI VA EL ARRAY DE ORDENES
  +ordenes
+'</tbody></table>'
+'<p lang="es-ES" class="western" style="margin-top: 0.01in"><br>'
+'</p>'
+'<table width="740" cellpadding="1" cellspacing="0">'
	+'<colgroup><col width="431">'
	+'<col width="189">'
	+'<col width="112">'
	+'</colgroup><tbody><tr valign="TOP">'
		+'<td width="431" height="12" style="border: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Observaciones (Otros)</b></font></font></font></p>'
		+'</td>'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total servicios gravados</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalservgravados+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td rowspan="10" width="431" height="12" style="border: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="font-weight: normal"><br>'
			+'</p>'
		+'</td>'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total servicios exentos</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalservexentos+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total mercancías gravadas</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalmercgravadas+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total mercancías exentas</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalmercexentas+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total gravado</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalgravado+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total exento</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalexento+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total venta</b></font></font></font></p>'
		+'</td>'
		'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalventa+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total descuento</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totaldescuento+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total venta neta</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalventaneta+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total impuestos</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalimpuestos+'</font></font></p>'
		+'</td>'
	+'</tr>'
	+'<tr valign="TOP">'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font color="#3f3f3f"><font size="1" style="font-size: 8pt"><b>Total comprobante</b></font></font></font></p>'
		+'</td>'
		+'<td width="112" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataFactura.totalcomprobante+'</font></font></p>'
		+'</td>'
	+'</tr>'
+'</tbody></table>'
+'<p lang="es-ES" class="western" style="margin-top: 0in"><br>'
+'</p>'
+'<p lang="es-ES" class="western" style="margin-left: 1.47in; margin-top: 0.07in"> Código Moneda..........	<span style="font-weight: normal">CRC</span></p>'
+'<p lang="es-ES" class="western" align="LEFT" style="margin-left: 1.47in; margin-top: 0.04in; font-weight: normal">'
+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt"><b>Tipo de cambio.........	</b></font><font size="1" style="font-size: 8pt">1.00000</font></font></p>'
+'<p lang="es-ES" class="western" style="margin-top: 0in; font-weight: normal; line-height: 100%">'
+'<br>'
+'</p>'
+'<p lang="es-ES" class="western" align="CENTER" style="margin-left: 2.23in; margin-right: 2.12in"> "Autorizada mediante resolución N° DGT-R-48-2016 del 07-10-2016 "</p> '
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" style="line-height: 100%"><br></p>'
+'<p lang="es-ES" class="western" align="RIGHT" style="margin-right: 1.53in; margin-top: 0.08in; font-weight: normal"> <font size="2" style="font-size: 11pt"><font face="Courier New, serif"><font size="2">PAGINA:1</font></font></font></p>'

'</body></html>';
	}
	resolve(content);
	});
}


function listaOrdenes(dataOrdenes){
	return new Promise((resolve, reject) => {

	if(dataOrdenes === "") {reject(undefined)}
	else{	
	var content='';
	for (var i = 0; i < dataOrdenes.length; i++) {
		
	
	content+='<tr valign="TOP">'
		+'<td width="35" height="34" style="border: 1px solid #BFBFBF; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].numerolineadetalle+'</font></font></p>'
		+'</td>'
		+'<td width="62" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">0</font></font></p>'
		+'</td>'
		+'<td width="189" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.03in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].descripcionproducto+'</font></font></p>'
		+'</td>'
		+'<td width="36" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="CENTER" style="margin-left: 0.01in; margin-right: 0.13in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].cantidadproducto+'</font></font></p>'
		+'</td>'
		+'<td width="49" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="JUSTIFY" style="margin-left: 0.03in; margin-right: 0.03in; margin-top: 0.05in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].unidadmedida+'</font></font></p>'
		+'</td>'
		+'<td width="87" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.4in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].preciounitarioproducto+'</font></font></p>'
		+'</td>'
		+'<td width="87" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.41in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].monto+'</font></font></p>'
		+'</td>'
		+'<td width="87" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" align="RIGHT" style="margin-right: 0.02in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].montodescuento+'</font></font></p>'
		+'</td>'
		+'<td width="87" style="border-top: 1px solid #000001; border-bottom: 1px solid #000001; border-left: 1px solid #000001; border-right: 1px solid #000001; padding-top: 0in; padding-bottom: 0in; padding-left: 0in; padding-right: 0in">'
			+'<p lang="es-ES" style="margin-left: 0.4in; margin-top: 0.03in; font-weight: normal">'
			+'<font size="2" style="font-size: 11pt"><font size="1" style="font-size: 8pt">'+dataOrdenes[i].montoitotallinea+'</font></font></p>'
		+'</td>'
	+'</tr><br>';
		}

		resolve(content);
		}
	})
	
}

module.exports= crearReporte();